import type { Criterion, Evaluation, GradingSession } from '../types/models';

interface ExportParams {
  gradingSession: GradingSession;
  rubricName: string;
  criteria: Criterion[];
  evaluations: Evaluation[];
}

const BRAND = 'D4566B';
const GREEN = '628141';
const AMBER = 'FF9800';
const RED = 'F44336';
const GRAY_HEADER = 'F5F5F5';
const WHITE = 'FFFFFF';

type ExcelCell = import('exceljs').Cell;

function percentageColor(pct: number): string {
  if (pct >= 70) return GREEN;
  if (pct >= 40) return AMBER;
  return RED;
}

function applyHeaderStyle(row: import('exceljs').Row, color: string = BRAND) {
  row.font = { bold: true, color: { argb: WHITE }, size: 11 };
  row.alignment = { horizontal: 'center', vertical: 'middle' };
  row.eachCell((cell: ExcelCell) => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: color } };
    cell.border = { bottom: { style: 'thin', color: { argb: 'CCCCCC' } } };
  });
}

function applyAlternatingRow(row: import('exceljs').Row, index: number) {
  if (index % 2 === 1) {
    row.eachCell((cell: ExcelCell) => {
      if (!cell.fill || (cell.fill as import('exceljs').FillPattern).fgColor?.argb === undefined) {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: GRAY_HEADER } };
      }
    });
  }
}

export async function exportGradingExcel(params: ExportParams): Promise<void> {
  const { gradingSession, rubricName, criteria, evaluations } = params;

  const ExcelJS = (await import('exceljs')).default;
  const wb = new ExcelJS.Workbook();
  wb.creator = 'LiveClass';
  wb.created = new Date();

  const sortedCriteria = [...criteria].sort((a, b) => a.order - b.order);
  const sortedEvals = [...evaluations].sort((a, b) => b.percentage - a.percentage);

  // Sheet 1: Summary
  const ws1 = wb.addWorksheet('Summary');

  ws1.mergeCells('A1:B1');
  const titleCell = ws1.getCell('A1');
  titleCell.value = `${gradingSession.name} — Summary`;
  titleCell.font = { bold: true, size: 14, color: { argb: WHITE } };
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND } };
  titleCell.alignment = { horizontal: 'center', vertical: 'middle' };
  ws1.getRow(1).height = 36;

  const scoredEvals = sortedEvals.filter((e) => e.totalScore > 0 || e.comment);
  const avgPct = scoredEvals.length > 0
    ? Math.round(scoredEvals.reduce((sum, e) => sum + e.percentage, 0) / scoredEvals.length)
    : 0;
  const avgScore = scoredEvals.length > 0
    ? Math.round(scoredEvals.reduce((sum, e) => sum + e.totalScore, 0) / scoredEvals.length * 10) / 10
    : 0;
  const maxScore = sortedEvals.length > 0 ? sortedEvals[0]?.maxPossibleScore || 0 : 0;

  const details: [string, string | number][] = [
    ['Session Name', gradingSession.name],
    ['Rubric', rubricName],
    ['Source Type', gradingSession.sourceType === 'session' ? 'LiveClass Session' : 'Roster'],
    ['Students Graded', `${scoredEvals.length} / ${sortedEvals.length}`],
    ['Average Score', `${avgScore} / ${maxScore}`],
    ['Average Percentage', `${avgPct}%`],
    ['Export Date', new Date().toLocaleString()],
    ['Generated By', 'LiveClass'],
  ];

  details.forEach(([label, value], i) => {
    const row = ws1.getRow(3 + i);
    row.values = [label, value];
    row.getCell(1).font = { bold: true, color: { argb: '555555' } };
    row.getCell(2).font = { size: 11 };
    if (i % 2 === 0) {
      row.eachCell((cell: ExcelCell) => {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: GRAY_HEADER } };
      });
    }
  });

  ws1.getColumn(1).width = 22;
  ws1.getColumn(2).width = 30;

  // Sheet 2: Student Scores
  const ws2 = wb.addWorksheet('Student Scores');

  const totalCols = 4 + sortedCriteria.length;
  ws2.mergeCells(1, 1, 1, totalCols);
  const titleCell2 = ws2.getCell('A1');
  titleCell2.value = `${gradingSession.name} — Student Scores`;
  titleCell2.font = { bold: true, size: 14, color: { argb: WHITE } };
  titleCell2.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND } };
  titleCell2.alignment = { horizontal: 'center', vertical: 'middle' };
  ws2.getRow(1).height = 36;

  const h2Row = 3;
  ws2.getRow(h2Row).values = [
    '#', 'Student Name', 'Student Number',
    ...sortedCriteria.map((c) => c.name),
    'Total', '%',
  ];
  applyHeaderStyle(ws2.getRow(h2Row));

  sortedEvals.forEach((evaluation, i) => {
    const rowNum = h2Row + 1 + i;
    const row = ws2.getRow(rowNum);

    const values: (string | number)[] = [
      i + 1,
      evaluation.studentName,
      evaluation.studentNumber || '—',
    ];

    for (const criterion of sortedCriteria) {
      const es = evaluation.scores[criterion.id];
      values.push(es ? es.score : 0);
    }

    values.push(evaluation.totalScore);
    values.push(Math.round(evaluation.percentage));

    row.values = values;
    row.alignment = { horizontal: 'center', vertical: 'middle' };
    row.getCell(2).alignment = { horizontal: 'left' };
    row.getCell(3).alignment = { horizontal: 'left' };

    // Percentage cell color
    const pctCell = row.getCell(values.length);
    pctCell.font = { bold: true, color: { argb: WHITE } };
    pctCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: percentageColor(evaluation.percentage) } };

    applyAlternatingRow(row, i);
  });

  ws2.getColumn(1).width = 5;
  ws2.getColumn(2).width = 25;
  ws2.getColumn(3).width = 16;
  for (let c = 0; c < sortedCriteria.length; c++) {
    ws2.getColumn(4 + c).width = 14;
  }
  ws2.getColumn(4 + sortedCriteria.length).width = 10;
  ws2.getColumn(5 + sortedCriteria.length).width = 8;

  // Sheet 3: Criteria Breakdown
  const ws3 = wb.addWorksheet('Criteria Breakdown');

  ws3.mergeCells('A1:F1');
  const titleCell3 = ws3.getCell('A1');
  titleCell3.value = `${gradingSession.name} — Criteria Analysis`;
  titleCell3.font = { bold: true, size: 14, color: { argb: WHITE } };
  titleCell3.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND } };
  titleCell3.alignment = { horizontal: 'center', vertical: 'middle' };
  ws3.getRow(1).height = 36;

  const h3Row = 3;
  ws3.getRow(h3Row).values = ['Criterion', 'Max Score', 'Weight', 'Avg Score', 'Min', 'Max'];
  applyHeaderStyle(ws3.getRow(h3Row));

  sortedCriteria.forEach((criterion, i) => {
    const scores = sortedEvals
      .map((e) => e.scores[criterion.id]?.score ?? 0)
      .filter((_, idx) => sortedEvals[idx].totalScore > 0 || sortedEvals[idx].comment);

    const avg = scores.length > 0 ? scores.reduce((a, b) => a + b, 0) / scores.length : 0;
    const min = scores.length > 0 ? Math.min(...scores) : 0;
    const max = scores.length > 0 ? Math.max(...scores) : 0;

    const rowNum = h3Row + 1 + i;
    const row = ws3.getRow(rowNum);
    row.values = [
      criterion.name,
      criterion.maxScore,
      criterion.weight,
      Math.round(avg * 10) / 10,
      min,
      max,
    ];
    row.alignment = { horizontal: 'center', vertical: 'middle' };
    row.getCell(1).alignment = { horizontal: 'left' };

    applyAlternatingRow(row, i);
  });

  ws3.columns = [
    { width: 25 }, { width: 12 }, { width: 10 },
    { width: 12 }, { width: 10 }, { width: 10 },
  ];

  // Download
  const buffer = await wb.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${gradingSession.name.replace(/[^a-zA-Z0-9 ]/g, '').trim() || 'grading'}_results.xlsx`;
  a.click();
  URL.revokeObjectURL(url);
}
