import type { ComponentType } from 'react';

/** A single round generated by the game module */
export interface MiniGameRound {
  type: string;          // Game-specific sub-type (e.g. 'dec2bin', 'addition')
  prompt: string;        // What to display to students
  answer: string;        // Correct answer (normalized string)
  timeLimitSec: number;
  /** Game-specific data (e.g. bits count, options for MCQ) */
  meta?: Record<string, unknown>;
}

/** Config field definition — drives the dynamic setup form */
export interface ConfigField {
  key: string;
  label: string;
  type: 'select' | 'multi-select' | 'number' | 'text';
  options?: { value: string; label: string }[];
  default: unknown;
  min?: number;
  max?: number;
}

/** Props passed to the game module's PlayerInput component */
export interface PlayerInputProps {
  round: MiniGameRound;
  onSubmit: (answer: string) => void;
  disabled: boolean;
}

/** Props passed to the game module's HostPrompt component */
export interface HostPromptProps {
  round: MiniGameRound;
  showAnswer: boolean;
}

/** The full game module definition */
export interface GameModule {
  /** Unique type key stored in Firestore (e.g. 'binary', 'subnet', 'port_blitz') */
  type: string;

  /** Display metadata */
  metadata: {
    name: string;
    description: string;
    icon: string;       // lucide-react icon name
    color: string;      // tailwind color key (e.g. 'brand', 'emerald', 'purple')
  };

  /** Config fields shown in the setup form (besides shared roundCount/timeLimitSec) */
  configFields: ConfigField[];

  /** Default config values (merged with shared defaults) */
  defaultConfig: Record<string, unknown>;

  /** React component for student answer input */
  PlayerInput: ComponentType<PlayerInputProps>;

  /** React component for the host/projector prompt display */
  HostPrompt: ComponentType<HostPromptProps>;

  /** Format a round's answer for display in results (optional, defaults to raw string) */
  formatAnswer?: (round: MiniGameRound) => string;

  /** Format a round's prompt for display in results (optional, defaults to raw string) */
  formatPrompt?: (round: MiniGameRound) => string;

  /** Label describing the conversion/task for a round (e.g. "DEC → BIN") */
  getRoundLabel?: (round: MiniGameRound) => string;
}
